apiVersion: v1
kind: ConfigMap
metadata:
  name: awms-config
  namespace: awms-prod
data:
  PROJECT_NAME: "Autonomous Warehouse Management System"
  DATABASE_URL: "sqlite:///./awms.db"
  MAX_FAILED_LOGIN_ATTEMPTS: "5"
